config/routes.rb
Firehoseapp::Application.routes.draw do
  devise_for :users

  resource :user, :only=> :show

  root :to => 'static_pages#index'
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  attr_accessible :hour, :emotion, :learned, :image

  mount_uploader :image, PictureUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  after_create :send_welcome_email

private


def send_welcome_email
	UserMailer.welcome_email(self).deliver
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	#new
	def new
		# hello ruby code here
		@pic = Pic.new
	end

	def index
		@pics = Pic.all
	end

	def create
		@pic = Pic.create(params[:pic])
		redirect_to pics_path

	end
		

	def show
	end

	def destroy
	end

	def edit
	end

	def update
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def show
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firehoseapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
	  <div class="navbar-inner">
		    <div class="container">
		 
		      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </a>
		 
		      <!-- Be sure to leave the brand out there if you want it shown -->
		      

		      <%= link_to('Web Development Apprentice', root_path, :class => 'brand' ) %>
		 
		      <!-- Everything you want hidden at 940px or less, place within here -->
		      <div class="nav-collapse collapse">
		        <!-- .nav, .navbar-search, .navbar-form, etc -->
		        <ul class="nav">
		        	<li>
		        		<%= link_to('My App', pics_path) %>
		        	</li>
		        	

		        	<% if current_user.blank? %>
		        	<li>
		        		<%= link_to('Sign In', new_user_session_path ) %>
						</li>

						<li>
		        		<%= link_to('Sign Up', new_user_registration_path ) %>
						</li>
		        	<% else %>

		        		<li>
		        		<%= link_to(current_user.email, user_path) %>
		        		</li>

		        		<li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>  </li>


		        	<% end %>
		        
		        	<%= link_to 'New Pic', new_pic_path,
		        			:class => 'btn btn-warning' %>

		        </ul>
		      </div>
		 
		    </div>
	  </div>
</div>

<% if notice.present? %>
	<p class="notice"><%= notice %></p>
<% end %>
<% if alert.present? %>
 	<p class="alert"><%= alert %></p>
 <% end %>
 

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<h2 class="custom-pic-header">Here are all the pics!</h2>



		<% @pics.each do |pic| %>
		<div class="span3">
		<div class="boxy">
			<H2>Hour: <%= pic.hour %></H2>
			<p />
			<%= image_tag pic.image %>
			<H4>Emotion: <br /><%= pic.emotion %></H4>
				<p />
				<br />
			<H5>What I Learned:</H5> <p><i><%= pic.learned %></i></p>
				<p />
			<p />
			
		</div>
		</div>

			
	<% end %>
	<br />

app/views/pics/new.html.erb
<div class="span6 offset3">
	<div class="boxy text-center">
	<h1 class="custom-pic-header">Add New Picture</h1>
</div>
	<div class="boxy text-center">


<%= simple_form_for @pic do |f| %>
	<%= f.input :hour %>
	<%= f.input :image, :as => :file %>
	<%= f.input :emotion %>
	<%= f.input :learned %>

	<%= submit_tag "Create", :class => 'btn-primary btn btn-large' %>

<% end %>
</div>

</div>

app/views/static_pages/index.html.erb
<div class="span6 offset3">

	<div class="boxy">

		<h1 class ="custom-font">Hi, I'm Ben</h1>


		<p>I'm at the firehose weekend at the cambridge innovation center. Installing was the most fun ever! Now we're making this shit happen.</p>
		<%= link_to('Check out my App', pics_path, :class => 'btn btn-success btn-large') %>

	</div>
</div>

app/views/users/show.html.erb
<div class="span6 offset3">
	<div class="boxy text-center">
	<h1 class="custom-pic-header">Add New Picture</h1>
</div>
	<div class="boxy text-center">
<h4>Hello, <%= current_user.email %></h4>
This page will be displayed when you are logged in and visit your user profile.


</div>
</div>